package chat.model;

import java.sql.Time;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name = "messages")
@NamedQueries({
    @NamedQuery(name = "chat.model.Message.findAll",
            query = "select e from Message e"),
    @NamedQuery(name = "chat.model.Message.findByName",
            query = "select e from Message e "
            + "where e.sender like :name "
            + "or e.receiver like :name"),
    @NamedQuery(name = "chat.model.Message.findByUser",
    query = "select e from Message e "
    + "where e.sender like :name "
    + "and e.receiver like :name1 ")
})

public class Message {
    /**
     * Entity's unique identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    /**
     * Message from.
     */
    @Column(name = "sender")
    private String sender;
    /**
     * Message to.
     */
    @Column(name = "receiver")
    private String receiver;
    /**
     * Message type
     */
    @Column(name = "message_type")
    private String messageType;
    
    
    /**
     * Message body.
     */
    private String body;
    
    @Column(name = "logg_time")
    private String logTime;
    
    /**
     * A no-argument constructor.
     */
    public Message() {
    }
    /**
     * A constructor to create Messages. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public Message(String sender, String receiver, String messageType, String body, String logTime) {
        this.sender = sender;
        this.receiver = receiver;
        this.messageType = messageType;
        this.body = body;
        this.logTime = logTime;
    }
    
    public String getLogTime() {
		return logTime;
	}
    
	public void setLogTime(String logTime) {
		this.logTime = logTime;
	}
	
	
	public long getId() {
		return id;
	}
	
	public void setId(long id) {
		this.id = id;
	}
	
	public String getSender() {
		return sender;
	}
	
	public void setSender(String sender) {
		this.sender = sender;
	}
	
	public String getReceiver() {
		return receiver;
	}
	
	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}
	
	public String getMessageType() {
		return messageType;
	}
	
	public void setMessageType(String MessageType) {
		this.messageType = MessageType;
	}
	
	public String getBody() {
		return body;
	}
	
	public void setBody(String Body) {
		this.body = Body;
	}
  }