package chat.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name = "messages")
@NamedQueries({
    @NamedQuery(name = "chat.model.Message.findAll",
            query = "select e from Message e"),
    @NamedQuery(name = "chat.model.Message.findByName",
            query = "select e from Message e "
            + "where e.from like :name "
            + "or e.to like :name")
})

public class Message {
    /**
     * Entity's unique identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    /**
     * Message from.
     */
    @Column(name = "from_user")
    private String from;
    /**
     * Message to.
     */
    @Column(name = "to_user")
    private String to;
    /**
     * Message type
     */
    @Column(name = "message_type")
    private String messageType;
    /**
     * Message body.
     */
    private String body;

    
    /**
     * A no-argument constructor.
     */
    public Message() {
    }
    /**
     * A constructor to create Messages. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public Message(String from, String to, String messageType, String body) {
        this.from = from;
        this.to = to;
        this.messageType = messageType;
        this.body = body;
    }
    // Auto-generated equald, hashCode, getters and setters.
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getFrom() {
		return from;
	}
	public void setFrom(String from) {
		this.from = from;
	}
	public String getTo() {
		return to;
	}
	public void setTo(String To) {
		this.to = To;
	}
	public String getMessageType() {
		return messageType;
	}
	public void setMessageType(String MessageType) {
		this.messageType = MessageType;
	}
	public String getBody() {
		return body;
	}
	public void setBody(String Body) {
		this.body = Body;
	}
	
	
  }