package chat.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name = "users")
@NamedQueries({
    @NamedQuery(name = "chat.model.User.findAll",
            query = "select e from User e"),
    @NamedQuery(name = "chat.model.User.findByName",
            query = "select e from User e "
            + "where e.username like :name "
            )
})

public class User {
    /**
     * Entity's unique identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    /**
     * User first name.
     */
    @Column(name = "username", unique=true)
    private String username;
    /**
     * User last name.
     */
    @Column(name = "password")
    private String password;
    /**
     * User position.
     */
    @Column(name = "security_question")
    private String securityQuestion;

    @Column(name = "security_answer")
    private String securityAnswer;
    
    private String password_salt;

    private String password_hash_algorithm;
    
    /**
     * A no-argument constructor.
     */
    public User() {
    }
    
    public String getPassword_salt() {
		return password_salt;
	}
    
	public void setPassword_salt(String password_salt) {
		this.password_salt = password_salt;
	}
	
	public String getPassword_hash_algorithm() {
		return password_hash_algorithm;
	}
	
	public void setPassword_hash_algorithm(String password_hash_algorithm) {
		this.password_hash_algorithm = password_hash_algorithm;
	}
	/**
     * A constructor to create user. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public User(String username, String password, String securityQuestion, String securityAnswer, String password_salt) {

        this.username = username;
        this.password = password;
        this.securityQuestion = securityQuestion;
        this.securityAnswer = securityAnswer;
        this.password_salt=password_salt;
       
        
    }
    
	public long getId() {
		return id;
	}
	
	public void setId(long id) {
		this.id = id;
	}
	
	public String getUsername() {
		return username;
	}
	
	public void setUsername(String username) {
		this.username = username;
	}
	
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getSecurityQuestion() {
		return securityQuestion;
	}
	
	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}
	
	public String getSecurityAnswer() {
		return securityAnswer;
	}
	
	public void setSecurityAnswer(String securityAnswer) {
		this.securityAnswer = securityAnswer;
	}

   
  }